version: '3.5'

services:
  spring_mvc-db:
    image: postgres:14.1
    container_name: library-db
    environment:
      - POSTGRES_PASSWORD=user
      - POSTGRES_USER=user
      - POSTGRES_DB=first_db
    ports:
      - "5500:5432"
    volumes:
      - ./yardata:/var/lib/postgresql/data